//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QueOfrecesEntities : DbContext
    {
        public QueOfrecesEntities()
            : base("name=QueOfrecesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA_OFERTA> CATEGORIA_OFERTA { get; set; }
        public DbSet<CUPON> CUPON { get; set; }
        public DbSet<DESCUENTO> DESCUENTO { get; set; }
        public DbSet<EMP> EMP { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<RETAIL> RETAIL { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<SUCURSALES> SUCURSALES { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
    }
}
