//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETAIL
    {
        public RETAIL()
        {
            this.SUCURSALES = new HashSet<SUCURSALES>();
        }
    
        public decimal ID_RETAIL { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
    
        public virtual ICollection<SUCURSALES> SUCURSALES { get; set; }
    }
}
