//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QOfreces.WPF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComprobarValoracion", ReplyAction="http://tempuri.org/IService1/ComprobarValoracionResponse")]
        string ComprobarValoracion(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComprobarValoracion", ReplyAction="http://tempuri.org/IService1/ComprobarValoracionResponse")]
        System.Threading.Tasks.Task<string> ComprobarValoracionAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValorarOferta", ReplyAction="http://tempuri.org/IService1/ValorarOfertaResponse")]
        string ValorarOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValorarOferta", ReplyAction="http://tempuri.org/IService1/ValorarOfertaResponse")]
        System.Threading.Tasks.Task<string> ValorarOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearUsuarioWeb", ReplyAction="http://tempuri.org/IService1/CrearUsuarioWebResponse")]
        string CrearUsuarioWeb(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearUsuarioWeb", ReplyAction="http://tempuri.org/IService1/CrearUsuarioWebResponse")]
        System.Threading.Tasks.Task<string> CrearUsuarioWebAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivarUsuario", ReplyAction="http://tempuri.org/IService1/ActivarUsuarioResponse")]
        string ActivarUsuario(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActivarUsuario", ReplyAction="http://tempuri.org/IService1/ActivarUsuarioResponse")]
        System.Threading.Tasks.Task<string> ActivarUsuarioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarComunas", ReplyAction="http://tempuri.org/IService1/ListarComunasResponse")]
        string ListarComunas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarComunas", ReplyAction="http://tempuri.org/IService1/ListarComunasResponse")]
        System.Threading.Tasks.Task<string> ListarComunasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRegiones", ReplyAction="http://tempuri.org/IService1/ListarRegionesResponse")]
        string ListarRegiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarRegiones", ReplyAction="http://tempuri.org/IService1/ListarRegionesResponse")]
        System.Threading.Tasks.Task<string> ListarRegionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarWeb", ReplyAction="http://tempuri.org/IService1/ValidarWebResponse")]
        string ValidarWeb(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarWeb", ReplyAction="http://tempuri.org/IService1/ValidarWebResponse")]
        System.Threading.Tasks.Task<string> ValidarWebAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuarioWPF", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioWPFResponse")]
        bool ValidarUsuarioWPF(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuarioWPF", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioWPFResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioWPFAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerUsuario", ReplyAction="http://tempuri.org/IService1/LeerUsuarioResponse")]
        string LeerUsuario(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerUsuario", ReplyAction="http://tempuri.org/IService1/LeerUsuarioResponse")]
        System.Threading.Tasks.Task<string> LeerUsuarioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearUsuario", ReplyAction="http://tempuri.org/IService1/CrearUsuarioResponse")]
        bool CrearUsuario(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearUsuario", ReplyAction="http://tempuri.org/IService1/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarUsuario", ReplyAction="http://tempuri.org/IService1/EliminarUsuarioResponse")]
        bool EliminarUsuario(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarUsuario", ReplyAction="http://tempuri.org/IService1/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarUsuario", ReplyAction="http://tempuri.org/IService1/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerId", ReplyAction="http://tempuri.org/IService1/LeerIdResponse")]
        string LeerId(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerId", ReplyAction="http://tempuri.org/IService1/LeerIdResponse")]
        System.Threading.Tasks.Task<string> LeerIdAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAll", ReplyAction="http://tempuri.org/IService1/ReadAllResponse")]
        string ReadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAll", ReplyAction="http://tempuri.org/IService1/ReadAllResponse")]
        System.Threading.Tasks.Task<string> ReadAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllProductos", ReplyAction="http://tempuri.org/IService1/ReadAllProductosResponse")]
        string ReadAllProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllProductos", ReplyAction="http://tempuri.org/IService1/ReadAllProductosResponse")]
        System.Threading.Tasks.Task<string> ReadAllProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRegiones", ReplyAction="http://tempuri.org/IService1/ReadAllRegionesResponse")]
        string ReadAllRegiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRegiones", ReplyAction="http://tempuri.org/IService1/ReadAllRegionesResponse")]
        System.Threading.Tasks.Task<string> ReadAllRegionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearRubro", ReplyAction="http://tempuri.org/IService1/CrearRubroResponse")]
        bool CrearRubro(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearRubro", ReplyAction="http://tempuri.org/IService1/CrearRubroResponse")]
        System.Threading.Tasks.Task<bool> CrearRubroAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarRubro", ReplyAction="http://tempuri.org/IService1/ActualizarRubroResponse")]
        bool ActualizarRubro(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarRubro", ReplyAction="http://tempuri.org/IService1/ActualizarRubroResponse")]
        System.Threading.Tasks.Task<bool> ActualizarRubroAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarRubro", ReplyAction="http://tempuri.org/IService1/EliminarRubroResponse")]
        bool EliminarRubro(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarRubro", ReplyAction="http://tempuri.org/IService1/EliminarRubroResponse")]
        System.Threading.Tasks.Task<bool> EliminarRubroAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRubros", ReplyAction="http://tempuri.org/IService1/ReadAllRubrosResponse")]
        string ReadAllRubros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRubros", ReplyAction="http://tempuri.org/IService1/ReadAllRubrosResponse")]
        System.Threading.Tasks.Task<string> ReadAllRubrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearPerfil", ReplyAction="http://tempuri.org/IService1/CrearPerfilResponse")]
        bool CrearPerfil(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearPerfil", ReplyAction="http://tempuri.org/IService1/CrearPerfilResponse")]
        System.Threading.Tasks.Task<bool> CrearPerfilAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPerfil", ReplyAction="http://tempuri.org/IService1/ActualizarPerfilResponse")]
        bool ActualizarPerfil(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarPerfil", ReplyAction="http://tempuri.org/IService1/ActualizarPerfilResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPerfilAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPerfil", ReplyAction="http://tempuri.org/IService1/EliminarPerfilResponse")]
        bool EliminarPerfil(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarPerfil", ReplyAction="http://tempuri.org/IService1/EliminarPerfilResponse")]
        System.Threading.Tasks.Task<bool> EliminarPerfilAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllPerfil", ReplyAction="http://tempuri.org/IService1/ReadAllPerfilResponse")]
        string ReadAllPerfil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllPerfil", ReplyAction="http://tempuri.org/IService1/ReadAllPerfilResponse")]
        System.Threading.Tasks.Task<string> ReadAllPerfilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearCategoria", ReplyAction="http://tempuri.org/IService1/CrearCategoriaResponse")]
        bool CrearCategoria(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearCategoria", ReplyAction="http://tempuri.org/IService1/CrearCategoriaResponse")]
        System.Threading.Tasks.Task<bool> CrearCategoriaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoria", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaResponse")]
        bool ActualizarCategoria(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarCategoria", ReplyAction="http://tempuri.org/IService1/ActualizarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCategoriaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCategoria", ReplyAction="http://tempuri.org/IService1/EliminarCategoriaResponse")]
        bool EliminarCategoria(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCategoria", ReplyAction="http://tempuri.org/IService1/EliminarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> EliminarCategoriaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllCategoria", ReplyAction="http://tempuri.org/IService1/ReadAllCategoriaResponse")]
        string ReadAllCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllCategoria", ReplyAction="http://tempuri.org/IService1/ReadAllCategoriaResponse")]
        System.Threading.Tasks.Task<string> ReadAllCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearSucursal", ReplyAction="http://tempuri.org/IService1/CrearSucursalResponse")]
        bool CrearSucursal(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearSucursal", ReplyAction="http://tempuri.org/IService1/CrearSucursalResponse")]
        System.Threading.Tasks.Task<bool> CrearSucursalAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarSucursal", ReplyAction="http://tempuri.org/IService1/ActualizarSucursalResponse")]
        bool ActualizarSucursal(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarSucursal", ReplyAction="http://tempuri.org/IService1/ActualizarSucursalResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSucursalAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarSucursal", ReplyAction="http://tempuri.org/IService1/EliminarSucursalResponse")]
        bool EliminarSucursal(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarSucursal", ReplyAction="http://tempuri.org/IService1/EliminarSucursalResponse")]
        System.Threading.Tasks.Task<bool> EliminarSucursalAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllSucursal", ReplyAction="http://tempuri.org/IService1/ReadAllSucursalResponse")]
        string ReadAllSucursal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllSucursal", ReplyAction="http://tempuri.org/IService1/ReadAllSucursalResponse")]
        System.Threading.Tasks.Task<string> ReadAllSucursalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllComuna", ReplyAction="http://tempuri.org/IService1/ReadAllComunaResponse")]
        string ReadAllComuna();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllComuna", ReplyAction="http://tempuri.org/IService1/ReadAllComunaResponse")]
        System.Threading.Tasks.Task<string> ReadAllComunaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasActivo", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasActivoResponse")]
        string ReadAllOfertasActivo(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasActivo", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasActivoResponse")]
        System.Threading.Tasks.Task<string> ReadAllOfertasActivoAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasDesactivo", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasDesactivoResponse")]
        string ReadAllOfertasDesactivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasDesactivo", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasDesactivoResponse")]
        System.Threading.Tasks.Task<string> ReadAllOfertasDesactivoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertas", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasResponse")]
        string ReadAllOfertas(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertas", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasResponse")]
        System.Threading.Tasks.Task<string> ReadAllOfertasAsync(int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasDia", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasDiaResponse")]
        string ReadAllOfertasDia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllOfertasDia", ReplyAction="http://tempuri.org/IService1/ReadAllOfertasDiaResponse")]
        System.Threading.Tasks.Task<string> ReadAllOfertasDiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearDesc", ReplyAction="http://tempuri.org/IService1/CrearDescResponse")]
        bool CrearDesc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearDesc", ReplyAction="http://tempuri.org/IService1/CrearDescResponse")]
        System.Threading.Tasks.Task<bool> CrearDescAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDesc", ReplyAction="http://tempuri.org/IService1/ActualizarDescResponse")]
        bool ActualizarDesc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDesc", ReplyAction="http://tempuri.org/IService1/ActualizarDescResponse")]
        System.Threading.Tasks.Task<bool> ActualizarDescAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarDesc", ReplyAction="http://tempuri.org/IService1/EliminarDescResponse")]
        bool EliminarDesc(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarDesc", ReplyAction="http://tempuri.org/IService1/EliminarDescResponse")]
        System.Threading.Tasks.Task<bool> EliminarDescAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearRetail", ReplyAction="http://tempuri.org/IService1/CrearRetailResponse")]
        bool CrearRetail(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearRetail", ReplyAction="http://tempuri.org/IService1/CrearRetailResponse")]
        System.Threading.Tasks.Task<bool> CrearRetailAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarRetail", ReplyAction="http://tempuri.org/IService1/ActualizarRetailResponse")]
        bool ActualizarRetail(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarRetail", ReplyAction="http://tempuri.org/IService1/ActualizarRetailResponse")]
        System.Threading.Tasks.Task<bool> ActualizarRetailAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarRetail", ReplyAction="http://tempuri.org/IService1/EliminarRetailResponse")]
        bool EliminarRetail(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarRetail", ReplyAction="http://tempuri.org/IService1/EliminarRetailResponse")]
        System.Threading.Tasks.Task<bool> EliminarRetailAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRetail", ReplyAction="http://tempuri.org/IService1/ReadAllRetailResponse")]
        string ReadAllRetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadAllRetail", ReplyAction="http://tempuri.org/IService1/ReadAllRetailResponse")]
        System.Threading.Tasks.Task<string> ReadAllRetailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearProducto", ReplyAction="http://tempuri.org/IService1/CrearProductoResponse")]
        bool CrearProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearProducto", ReplyAction="http://tempuri.org/IService1/CrearProductoResponse")]
        System.Threading.Tasks.Task<bool> CrearProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        bool ActualizarProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarProducto", ReplyAction="http://tempuri.org/IService1/EliminarProductoResponse")]
        bool EliminarProducto(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarProducto", ReplyAction="http://tempuri.org/IService1/EliminarProductoResponse")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerOferta", ReplyAction="http://tempuri.org/IService1/TraerOfertaResponse")]
        string TraerOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerOferta", ReplyAction="http://tempuri.org/IService1/TraerOfertaResponse")]
        System.Threading.Tasks.Task<string> TraerOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearOferta", ReplyAction="http://tempuri.org/IService1/CrearOfertaResponse")]
        bool CrearOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearOferta", ReplyAction="http://tempuri.org/IService1/CrearOfertaResponse")]
        System.Threading.Tasks.Task<bool> CrearOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarOferta", ReplyAction="http://tempuri.org/IService1/ActualizarOfertaResponse")]
        bool ActualizarOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarOferta", ReplyAction="http://tempuri.org/IService1/ActualizarOfertaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarOferta", ReplyAction="http://tempuri.org/IService1/EliminarOfertaResponse")]
        bool EliminarOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarOferta", ReplyAction="http://tempuri.org/IService1/EliminarOfertaResponse")]
        System.Threading.Tasks.Task<bool> EliminarOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerOfertaId", ReplyAction="http://tempuri.org/IService1/LeerOfertaIdResponse")]
        string LeerOfertaId(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LeerOfertaId", ReplyAction="http://tempuri.org/IService1/LeerOfertaIdResponse")]
        System.Threading.Tasks.Task<string> LeerOfertaIdAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OfertaParametro", ReplyAction="http://tempuri.org/IService1/OfertaParametroResponse")]
        string OfertaParametro(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OfertaParametro", ReplyAction="http://tempuri.org/IService1/OfertaParametroResponse")]
        System.Threading.Tasks.Task<string> OfertaParametroAsync(string parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PublicarOferta", ReplyAction="http://tempuri.org/IService1/PublicarOfertaResponse")]
        bool PublicarOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PublicarOferta", ReplyAction="http://tempuri.org/IService1/PublicarOfertaResponse")]
        System.Threading.Tasks.Task<bool> PublicarOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DesPublicarOferta", ReplyAction="http://tempuri.org/IService1/DesPublicarOfertaResponse")]
        bool DesPublicarOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DesPublicarOferta", ReplyAction="http://tempuri.org/IService1/DesPublicarOfertaResponse")]
        System.Threading.Tasks.Task<bool> DesPublicarOfertaAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Data", ReplyAction="http://tempuri.org/IService1/DataResponse")]
        string Data();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Data", ReplyAction="http://tempuri.org/IService1/DataResponse")]
        System.Threading.Tasks.Task<string> DataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearProductoHasOferta", ReplyAction="http://tempuri.org/IService1/CrearProductoHasOfertaResponse")]
        bool CrearProductoHasOferta(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrearProductoHasOferta", ReplyAction="http://tempuri.org/IService1/CrearProductoHasOfertaResponse")]
        System.Threading.Tasks.Task<bool> CrearProductoHasOfertaAsync(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : QOfreces.WPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<QOfreces.WPF.ServiceReference1.IService1>, QOfreces.WPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ComprobarValoracion(string json) {
            return base.Channel.ComprobarValoracion(json);
        }
        
        public System.Threading.Tasks.Task<string> ComprobarValoracionAsync(string json) {
            return base.Channel.ComprobarValoracionAsync(json);
        }
        
        public string ValorarOferta(string json) {
            return base.Channel.ValorarOferta(json);
        }
        
        public System.Threading.Tasks.Task<string> ValorarOfertaAsync(string json) {
            return base.Channel.ValorarOfertaAsync(json);
        }
        
        public string CrearUsuarioWeb(string json) {
            return base.Channel.CrearUsuarioWeb(json);
        }
        
        public System.Threading.Tasks.Task<string> CrearUsuarioWebAsync(string json) {
            return base.Channel.CrearUsuarioWebAsync(json);
        }
        
        public string ActivarUsuario(string json) {
            return base.Channel.ActivarUsuario(json);
        }
        
        public System.Threading.Tasks.Task<string> ActivarUsuarioAsync(string json) {
            return base.Channel.ActivarUsuarioAsync(json);
        }
        
        public string ListarComunas() {
            return base.Channel.ListarComunas();
        }
        
        public System.Threading.Tasks.Task<string> ListarComunasAsync() {
            return base.Channel.ListarComunasAsync();
        }
        
        public string ListarRegiones() {
            return base.Channel.ListarRegiones();
        }
        
        public System.Threading.Tasks.Task<string> ListarRegionesAsync() {
            return base.Channel.ListarRegionesAsync();
        }
        
        public string ValidarWeb(string json) {
            return base.Channel.ValidarWeb(json);
        }
        
        public System.Threading.Tasks.Task<string> ValidarWebAsync(string json) {
            return base.Channel.ValidarWebAsync(json);
        }
        
        public bool ValidarUsuarioWPF(string username, string password) {
            return base.Channel.ValidarUsuarioWPF(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioWPFAsync(string username, string password) {
            return base.Channel.ValidarUsuarioWPFAsync(username, password);
        }
        
        public string LeerUsuario(string json) {
            return base.Channel.LeerUsuario(json);
        }
        
        public System.Threading.Tasks.Task<string> LeerUsuarioAsync(string json) {
            return base.Channel.LeerUsuarioAsync(json);
        }
        
        public bool CrearUsuario(string json) {
            return base.Channel.CrearUsuario(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string json) {
            return base.Channel.CrearUsuarioAsync(json);
        }
        
        public bool EliminarUsuario(string json) {
            return base.Channel.EliminarUsuario(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string json) {
            return base.Channel.EliminarUsuarioAsync(json);
        }
        
        public bool ActualizarUsuario(string json) {
            return base.Channel.ActualizarUsuario(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(string json) {
            return base.Channel.ActualizarUsuarioAsync(json);
        }
        
        public string LeerId(string json) {
            return base.Channel.LeerId(json);
        }
        
        public System.Threading.Tasks.Task<string> LeerIdAsync(string json) {
            return base.Channel.LeerIdAsync(json);
        }
        
        public string ReadAll() {
            return base.Channel.ReadAll();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllAsync() {
            return base.Channel.ReadAllAsync();
        }
        
        public string ReadAllProductos() {
            return base.Channel.ReadAllProductos();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllProductosAsync() {
            return base.Channel.ReadAllProductosAsync();
        }
        
        public string ReadAllRegiones() {
            return base.Channel.ReadAllRegiones();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllRegionesAsync() {
            return base.Channel.ReadAllRegionesAsync();
        }
        
        public bool CrearRubro(string json) {
            return base.Channel.CrearRubro(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearRubroAsync(string json) {
            return base.Channel.CrearRubroAsync(json);
        }
        
        public bool ActualizarRubro(string json) {
            return base.Channel.ActualizarRubro(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarRubroAsync(string json) {
            return base.Channel.ActualizarRubroAsync(json);
        }
        
        public bool EliminarRubro(string json) {
            return base.Channel.EliminarRubro(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarRubroAsync(string json) {
            return base.Channel.EliminarRubroAsync(json);
        }
        
        public string ReadAllRubros() {
            return base.Channel.ReadAllRubros();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllRubrosAsync() {
            return base.Channel.ReadAllRubrosAsync();
        }
        
        public bool CrearPerfil(string json) {
            return base.Channel.CrearPerfil(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearPerfilAsync(string json) {
            return base.Channel.CrearPerfilAsync(json);
        }
        
        public bool ActualizarPerfil(string json) {
            return base.Channel.ActualizarPerfil(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPerfilAsync(string json) {
            return base.Channel.ActualizarPerfilAsync(json);
        }
        
        public bool EliminarPerfil(string json) {
            return base.Channel.EliminarPerfil(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarPerfilAsync(string json) {
            return base.Channel.EliminarPerfilAsync(json);
        }
        
        public string ReadAllPerfil() {
            return base.Channel.ReadAllPerfil();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllPerfilAsync() {
            return base.Channel.ReadAllPerfilAsync();
        }
        
        public bool CrearCategoria(string json) {
            return base.Channel.CrearCategoria(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCategoriaAsync(string json) {
            return base.Channel.CrearCategoriaAsync(json);
        }
        
        public bool ActualizarCategoria(string json) {
            return base.Channel.ActualizarCategoria(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCategoriaAsync(string json) {
            return base.Channel.ActualizarCategoriaAsync(json);
        }
        
        public bool EliminarCategoria(string json) {
            return base.Channel.EliminarCategoria(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCategoriaAsync(string json) {
            return base.Channel.EliminarCategoriaAsync(json);
        }
        
        public string ReadAllCategoria() {
            return base.Channel.ReadAllCategoria();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllCategoriaAsync() {
            return base.Channel.ReadAllCategoriaAsync();
        }
        
        public bool CrearSucursal(string json) {
            return base.Channel.CrearSucursal(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearSucursalAsync(string json) {
            return base.Channel.CrearSucursalAsync(json);
        }
        
        public bool ActualizarSucursal(string json) {
            return base.Channel.ActualizarSucursal(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSucursalAsync(string json) {
            return base.Channel.ActualizarSucursalAsync(json);
        }
        
        public bool EliminarSucursal(string json) {
            return base.Channel.EliminarSucursal(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSucursalAsync(string json) {
            return base.Channel.EliminarSucursalAsync(json);
        }
        
        public string ReadAllSucursal() {
            return base.Channel.ReadAllSucursal();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllSucursalAsync() {
            return base.Channel.ReadAllSucursalAsync();
        }
        
        public string ReadAllComuna() {
            return base.Channel.ReadAllComuna();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllComunaAsync() {
            return base.Channel.ReadAllComunaAsync();
        }
        
        public string ReadAllOfertasActivo(int idSucursal) {
            return base.Channel.ReadAllOfertasActivo(idSucursal);
        }
        
        public System.Threading.Tasks.Task<string> ReadAllOfertasActivoAsync(int idSucursal) {
            return base.Channel.ReadAllOfertasActivoAsync(idSucursal);
        }
        
        public string ReadAllOfertasDesactivo() {
            return base.Channel.ReadAllOfertasDesactivo();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllOfertasDesactivoAsync() {
            return base.Channel.ReadAllOfertasDesactivoAsync();
        }
        
        public string ReadAllOfertas(int idSucursal) {
            return base.Channel.ReadAllOfertas(idSucursal);
        }
        
        public System.Threading.Tasks.Task<string> ReadAllOfertasAsync(int idSucursal) {
            return base.Channel.ReadAllOfertasAsync(idSucursal);
        }
        
        public string ReadAllOfertasDia() {
            return base.Channel.ReadAllOfertasDia();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllOfertasDiaAsync() {
            return base.Channel.ReadAllOfertasDiaAsync();
        }
        
        public bool CrearDesc(string json) {
            return base.Channel.CrearDesc(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearDescAsync(string json) {
            return base.Channel.CrearDescAsync(json);
        }
        
        public bool ActualizarDesc(string json) {
            return base.Channel.ActualizarDesc(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarDescAsync(string json) {
            return base.Channel.ActualizarDescAsync(json);
        }
        
        public bool EliminarDesc(string json) {
            return base.Channel.EliminarDesc(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDescAsync(string json) {
            return base.Channel.EliminarDescAsync(json);
        }
        
        public bool CrearRetail(string json) {
            return base.Channel.CrearRetail(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearRetailAsync(string json) {
            return base.Channel.CrearRetailAsync(json);
        }
        
        public bool ActualizarRetail(string json) {
            return base.Channel.ActualizarRetail(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarRetailAsync(string json) {
            return base.Channel.ActualizarRetailAsync(json);
        }
        
        public bool EliminarRetail(string json) {
            return base.Channel.EliminarRetail(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarRetailAsync(string json) {
            return base.Channel.EliminarRetailAsync(json);
        }
        
        public string ReadAllRetail() {
            return base.Channel.ReadAllRetail();
        }
        
        public System.Threading.Tasks.Task<string> ReadAllRetailAsync() {
            return base.Channel.ReadAllRetailAsync();
        }
        
        public bool CrearProducto(string json) {
            return base.Channel.CrearProducto(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearProductoAsync(string json) {
            return base.Channel.CrearProductoAsync(json);
        }
        
        public bool ActualizarProducto(string json) {
            return base.Channel.ActualizarProducto(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProductoAsync(string json) {
            return base.Channel.ActualizarProductoAsync(json);
        }
        
        public bool EliminarProducto(string json) {
            return base.Channel.EliminarProducto(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(string json) {
            return base.Channel.EliminarProductoAsync(json);
        }
        
        public string TraerOferta(string json) {
            return base.Channel.TraerOferta(json);
        }
        
        public System.Threading.Tasks.Task<string> TraerOfertaAsync(string json) {
            return base.Channel.TraerOfertaAsync(json);
        }
        
        public bool CrearOferta(string json) {
            return base.Channel.CrearOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearOfertaAsync(string json) {
            return base.Channel.CrearOfertaAsync(json);
        }
        
        public bool ActualizarOferta(string json) {
            return base.Channel.ActualizarOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarOfertaAsync(string json) {
            return base.Channel.ActualizarOfertaAsync(json);
        }
        
        public bool EliminarOferta(string json) {
            return base.Channel.EliminarOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarOfertaAsync(string json) {
            return base.Channel.EliminarOfertaAsync(json);
        }
        
        public string LeerOfertaId(string json) {
            return base.Channel.LeerOfertaId(json);
        }
        
        public System.Threading.Tasks.Task<string> LeerOfertaIdAsync(string json) {
            return base.Channel.LeerOfertaIdAsync(json);
        }
        
        public string OfertaParametro(string parametro) {
            return base.Channel.OfertaParametro(parametro);
        }
        
        public System.Threading.Tasks.Task<string> OfertaParametroAsync(string parametro) {
            return base.Channel.OfertaParametroAsync(parametro);
        }
        
        public bool PublicarOferta(string json) {
            return base.Channel.PublicarOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> PublicarOfertaAsync(string json) {
            return base.Channel.PublicarOfertaAsync(json);
        }
        
        public bool DesPublicarOferta(string json) {
            return base.Channel.DesPublicarOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> DesPublicarOfertaAsync(string json) {
            return base.Channel.DesPublicarOfertaAsync(json);
        }
        
        public string Data() {
            return base.Channel.Data();
        }
        
        public System.Threading.Tasks.Task<string> DataAsync() {
            return base.Channel.DataAsync();
        }
        
        public bool CrearProductoHasOferta(string json) {
            return base.Channel.CrearProductoHasOferta(json);
        }
        
        public System.Threading.Tasks.Task<bool> CrearProductoHasOfertaAsync(string json) {
            return base.Channel.CrearProductoHasOfertaAsync(json);
        }
    }
}
