//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public decimal ID_PRODUCTO { get; set; }
        public decimal RUBRO_ID { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public string SKU { get; set; }
        public string CODIGO_INTERNO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual RUBRO RUBRO { get; set; }
    }
}
