//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSALES
    {
        public SUCURSALES()
        {
            this.OFERTA = new HashSet<OFERTA>();
        }
    
        public decimal ID_SUCURSAL { get; set; }
        public string RUT { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public Nullable<decimal> COMUNA_ID { get; set; }
        public Nullable<decimal> REGION_ID { get; set; }
        public string EMAIL { get; set; }
        public decimal RETAIL_ID { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<OFERTA> OFERTA { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual RETAIL RETAIL { get; set; }
    }
}
