//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPORTAMIENTO
    {
        public decimal ID_COMPORTAMIENTO { get; set; }
        public Nullable<decimal> PRODUCTO_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
