//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPON
    {
        public decimal ID_CUPON { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_HASTA { get; set; }
        public decimal ACTIVO { get; set; }
        public decimal USUARIO_ID { get; set; }
        public Nullable<decimal> DESCUENTO_ID { get; set; }
        public string CODIGO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
