//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTO
    {
        public decimal ID_DESCUENTO { get; set; }
        public Nullable<decimal> MIN_PUNTOS { get; set; }
        public Nullable<decimal> MAX_PUNTOS { get; set; }
        public decimal PORCENTAJE { get; set; }
        public decimal TOPE { get; set; }
    }
}
