//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTO_HAS_RUBRO
    {
        public Nullable<decimal> DESCUENTO_ID { get; set; }
        public Nullable<decimal> RUBRO_ID { get; set; }
        public decimal ID_DESCUENTO_RUBRO { get; set; }
    }
}
