//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CUPON = new HashSet<CUPON>();
            this.VALORACION = new HashSet<VALORACION>();
        }
    
        public decimal ID_USUARIO { get; set; }
        public decimal PERFIL_ID { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string RUT { get; set; }
        public string ACTIVO { get; set; }
        public decimal SUCURSAL_ID { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string SEXO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string PASSAPORTE { get; set; }
        public Nullable<decimal> COMUNA_ID { get; set; }
        public Nullable<decimal> REGION_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> NUMERO_CELULAR { get; set; }
        public Nullable<decimal> PUNTOS { get; set; }
        public string CODIGO_VERIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<CUPON> CUPON { get; set; }
        public virtual PERFIL PERFIL { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
    }
}
