//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORACION
    {
        public decimal ID_VALORACION { get; set; }
        public string CODE_IMAGEN { get; set; }
        public string CALIFICACION { get; set; }
        public string RUBRO { get; set; }
        public decimal USUARIO_ID { get; set; }
        public decimal OFERTA_ID { get; set; }
        public Nullable<System.DateTime> FECHA_VALORACION { get; set; }
        public string COMENTARIO { get; set; }
    
        public virtual OFERTA OFERTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
